# MA3K7 Assignment 5
### Due: 20 Mar 2024

In [33]:
## import libraries

import numpy as np
import matplotlib.pyplot as plt
import random
import math

In [34]:
## defining a matrix
n = 9
M = np.zeros(shape=(n,n))
print(M)

[[0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [5]:
## n must be odd
n=9
M = np.zeros(shape=(n,n))
ceil = math.ceil(n/2)

for itns in range(1,ceil+1):
    n= (2*ceil+1)-2*itns

    for i in range(n**2-(n-1), n**2+1):
        M[n-1+itns-1][(n-1)-((n**2)-i)+itns-1] = i

    for j in range(n**2-2*(n-1),n**2-n+1):
        M[(n-2)-((n**2-n)-j)+itns-1][itns-1] = j
        
    for k in range(n**2-2*(n-1)-1, n**2-3*(n-1)-1, -1): 
        M[itns-1][(n**2-2*(n-1)-k)+itns-1] = k
        
    for l in range(n**2-3*(n-1)-1, n**2-4*(n-1), -1):
        M[(n**2-3*(n-1)-l)+itns-1][n-1+itns-1] = l
    

print(M)

[[65. 64. 63. 62. 61. 60. 59. 58. 57.]
 [66. 37. 36. 35. 34. 33. 32. 31. 56.]
 [67. 38. 17. 16. 15. 14. 13. 30. 55.]
 [68. 39. 18.  5.  4.  3. 12. 29. 54.]
 [69. 40. 19.  6.  1.  2. 11. 28. 53.]
 [70. 41. 20.  7.  8.  9. 10. 27. 52.]
 [71. 42. 21. 22. 23. 24. 25. 26. 51.]
 [72. 43. 44. 45. 46. 47. 48. 49. 50.]
 [73. 74. 75. 76. 77. 78. 79. 80. 81.]]


In [3]:
## n must be even
n=8
M = np.zeros(shape=(n,n))
ceil = math.ceil(n/2)

for itns in range(1,ceil+1):
    n= (2*ceil+2)-2*itns

    for i in range(n**2, n**2-(n-1)-1,-1):
        M[itns-1][((n**2)-i)+itns-1] = i

    for j in range(n**2-(n-1),n**2-2*(n-1)-1,-1):
        M[((n**2-(n-1))-j)+itns-1][n-1+itns-1] = j
        
    for k in range(n**2-3*(n-1), n**2-2*(n-1)): 
        M[n-1+itns-1][(n-1)-(n**2-2*(n-1)-k)+itns-1] = k
        
    for l in range(n**2-4*(n-1)+1, n**2-3*(n-1)+1):
        M[(n-1)-(n**2-3*(n-1)-l)+itns-1][itns-1] = l
    

print(M)

[[64. 63. 62. 61. 60. 59. 58. 57.]
 [37. 36. 35. 34. 33. 32. 31. 56.]
 [38. 17. 16. 15. 14. 13. 30. 55.]
 [39. 18.  5.  4.  3. 12. 29. 54.]
 [40. 19.  6.  1.  2. 11. 28. 53.]
 [41. 20.  7.  8.  9. 10. 27. 52.]
 [42. 21. 22. 23. 24. 25. 26. 51.]
 [43. 44. 45. 46. 47. 48. 49. 50.]]


In [31]:
## spiral starting by going left and spiralling clockwise outwards 
n=9
M = np.zeros(shape=(n,n))
ceil = math.ceil(n/2)

for itns in range(1,ceil+1):
    n= (2*ceil+1)-2*itns

    for i in range(n**2,n**2-(n-1)-1,-1):
        M[n-1+itns-1][((n**2)-i)+itns-1] = i

    for j in range(n**2-n,n**2-2*(n-1)-1,-1):
        M[(n-2)-((n**2-n)-j)+itns-1][n-1+itns-1] = j
        
    for k in range(n**2-3*(n-1),n**2-2*(n-1)): 
        M[itns-1][(n-1)-(n**2-2*(n-1)-k)+itns-1] = k
        
    for l in range(n**2-4*(n-1)+1,n**2-3*(n-1)):
        M[(n**2-3*(n-1)-l)+itns-1][itns-1] = l
    

print(M)

[[57. 58. 59. 60. 61. 62. 63. 64. 65.]
 [56. 31. 32. 33. 34. 35. 36. 37. 66.]
 [55. 30. 13. 14. 15. 16. 17. 38. 67.]
 [54. 29. 12.  3.  4.  5. 18. 39. 68.]
 [53. 28. 11.  2.  1.  6. 19. 40. 69.]
 [52. 27. 10.  9.  8.  7. 20. 41. 70.]
 [51. 26. 25. 24. 23. 22. 21. 42. 71.]
 [50. 49. 48. 47. 46. 45. 44. 43. 72.]
 [81. 80. 79. 78. 77. 76. 75. 74. 73.]]
